let img1 = document.querySelectorAll(".image-holder1 img")
let img2 = document.querySelectorAll(".image-holder2 img")
let img3 = document.querySelectorAll(".image-holder3 img")
let count = 1;
let myProgress= document.querySelector(".progress");
let myLine= window.getComputedStyle(myProgress,"::before"); 
let main_transition1=function(){
    if(count==1){
        myProgress.style.setProperty('--beforeWidth','10%')
        img1[1].style.transform="translateX(-100%)";
    }
    if(count==2){
        myProgress.style.setProperty('--beforeWidth','20%')
        img1[2].style.transform="translateX(-200%)"
    }
    if(count==3){
        myProgress.style.setProperty('--beforeWidth','30%')
        img1[3].style.transform="translateX(-300%)"
    }
    if(count==4){
        
        img1[4].style.transform="translateX(-400%)"
        myProgress.style.setProperty('--beforeWidth','40%')
    }
    if(count==5){
        
        img1[5].style.transform="translateX(-500%)"
        myProgress.style.setProperty('--beforeWidth','50%')
    }
    if(count==6){
        
        img1[6].style.transform="translateX(-600%)"
        myProgress.style.setProperty('--beforeWidth','60%')
    }
    if(count==7){
        img1[1].style.transform="translateX(0)"
        img1[2].style.transform="translateX(0)"
        img1[3].style.transform="translateX(0)"
        img1[4].style.transform="translateX(0)"
        img1[5].style.transform="translateX(0)"
        img1[6].style.transform="translateX(0)"
        myProgress.style.setProperty('--beforeWidth','3%')        
    }
}
let main_back_transition1=function(){
    if(count==1){
        img1[5].style.transform="translateX(-500%)"
        img1[6].style.transform="translateX(-600%)"
        myProgress.style.setProperty('--beforeWidth','60%')
    }
    if(count==2){
        img1[0].style.transform="translateX(0)"
        img1[1].style.transform="translateX(0)"
        img1[2].style.transform="translateX(0)"
        img1[3].style.transform="translateX(0)"
        img1[4].style.transform="translateX(0)"
        img1[5].style.transform="translateX(0)"
        img1[6].style.transform="translateX(0)"
        myProgress.style.setProperty('--beforeWidth','3%')
    }
    if(count==3){
        img1[1].style.transform="translateX(-100%)"
        img1[2].style.transform="translateX(0)"
        img1[3].style.transform="translateX(0)"
        img1[4].style.transform="translateX(0)"
        img1[5].style.transform="translateX(0)"
        img1[6].style.transform="translateX(0)"
        
        myProgress.style.setProperty('--beforeWidth','10%')
    }
    if(count==4){
        img1[1].style.transform="translateX(-100%)"
        img1[2].style.transform="translateX(-200%)"
        img1[3].style.transform="translateX(0)"
        img1[4].style.transform="translateX(0)"
        img1[5].style.transform="translateX(0)"
        img1[6].style.transform="translateX(0)"
        myProgress.style.setProperty('--beforeWidth','20%')
    }
    if(count==5){
        img1[2].style.transform="translateX(-200%)"
        img1[3].style.transform="translateX(-300%)"
        img1[4].style.transform="translateX(0)"
        img1[5].style.transform="translateX(0)"
        img1[6].style.transform="translateX(0)"
        myProgress.style.setProperty('--beforeWidth','30%')
    }
    if(count==6){
        img1[3].style.transform="translateX(-300%)"
        img1[4].style.transform="translateX(-400%)"
        img1[5].style.transform="translateX(0)"
        img1[6].style.transform="translateX(0)"
        myProgress.style.setProperty('--beforeWidth','40%')   
    }   
    if(count==7){
        img1[4].style.transform="translateX(-400%)"
        img1[5].style.transform="translateX(-500%)"
        img1[6].style.transform="translateX(0)"
        myProgress.style.setProperty('--beforeWidth','50%');
    }
}
let main_transition2=function(){
    if(count==1){
        img2[1].style.transform="translateX(-100%)";
    }
    if(count==2){
        img2[2].style.transform="translateX(-200%)"
    }
    if(count==3){
        img2[3].style.transform="translateX(-300%)"
    }
    if(count==4){
        img2[4].style.transform="translateX(-400%)"
    }
    if(count==5){
        img2[5].style.transform="translateX(-500%)"
    }
    if(count==6){
        img2[6].style.transform="translateX(-600%)"
    }
    if(count==7){
        img2[1].style.transform="translateX(0)"
        img2[2].style.transform="translateX(0)"
        img2[3].style.transform="translateX(0)"
        img2[4].style.transform="translateX(0)"
        img2[5].style.transform="translateX(0)"
        img2[6].style.transform="translateX(0)"
    }
    }
    let main_back_transition2=function(){
        if(count==1){
            img2[5].style.transform="translateX(-500%)"
            img2[6].style.transform="translateX(-600%)"
            myProgress.style.setProperty('--beforeWidth','60%')       
        }
        if(count==2){
            img2[0].style.transform="translateX(0)"
            img2[1].style.transform="translateX(0)"
            img2[2].style.transform="translateX(0)"
            img2[3].style.transform="translateX(0)"
            img2[4].style.transform="translateX(0)"
            img2[5].style.transform="translateX(0)"
            img2[6].style.transform="translateX(0)"
            myProgress.style.setProperty('--beforeWidth','3%')
        }
        if(count==3){
            img2[1].style.transform="translateX(-100%)"
            img2[2].style.transform="translateX(0)"
            img2[3].style.transform="translateX(0)"
            img2[4].style.transform="translateX(0)"
            img2[5].style.transform="translateX(0)"
            img2[6].style.transform="translateX(0)"   
            myProgress.style.setProperty('--beforeWidth','10%')
        }
        if(count==4){
            img2[1].style.transform="translateX(-100%)"
            img2[2].style.transform="translateX(-200%)"
            img2[3].style.transform="translateX(0)"
            img2[4].style.transform="translateX(0)"
            img2[5].style.transform="translateX(0)"
            img2[6].style.transform="translateX(0)"
            myProgress.style.setProperty('--beforeWidth','20%')
        }
        if(count==5){
            img2[2].style.transform="translateX(-200%)"
            img2[3].style.transform="translateX(-300%)"
            img2[4].style.transform="translateX(0)"
            img2[5].style.transform="translateX(0)"
            img2[6].style.transform="translateX(0)"
            myProgress.style.setProperty('--beforeWidth','30%')
        }
        if(count==6){
            img2[3].style.transform="translateX(-300%)"
            img2[4].style.transform="translateX(-400%)"
            img2[5].style.transform="translateX(0)"
            img2[6].style.transform="translateX(0)"
            myProgress.style.setProperty('--beforeWidth','40%')
        }
        if(count==7){
            img2[4].style.transform="translateX(-400%)"
            img2[5].style.transform="translateX(-500%)"
            img2[6].style.transform="translateX(0)"
            myProgress.style.setProperty('--beforeWidth','50%');   
        }
    }
    let main_transition3=function(){
        if(count==1){
            img3[1].style.transform="translateX(-100%)";
        }
        if(count==2){
            img3[2].style.transform="translateX(-200%)"
        }
        if(count==3){
            img3[3].style.transform="translateX(-300%)"
        }
        if(count==4){
            img3[4].style.transform="translateX(-400%)"
        }
        if(count==5){
            img3[5].style.transform="translateX(-500%)"
        }
        if(count==6){
            img3[6].style.transform="translateX(-600%)"
        }
        if(count==7){
            img3[1].style.transform="translateX(0)"
            img3[2].style.transform="translateX(0)"
            img3[3].style.transform="translateX(0)"
            img3[4].style.transform="translateX(0)"
            img3[5].style.transform="translateX(0)"
            img3[6].style.transform="translateX(0)"
            count=0;
        }
        count++;
        }
        let main_back_transition3=function(){
            if(count==1){
                img3[5].style.transform="translateX(-500%)"
                img3[6].style.transform="translateX(-600%)"
                myProgress.style.setProperty('--beforeWidth','60%')
                count=8;
            }
            if(count==2){
                img3[0].style.transform="translateX(0)"
                img3[1].style.transform="translateX(0)"
                img3[2].style.transform="translateX(0)"
                img3[3].style.transform="translateX(0)"
                img3[4].style.transform="translateX(0)"
                img3[5].style.transform="translateX(0)"
                img3[6].style.transform="translateX(0)"
                myProgress.style.setProperty('--beforeWidth','3%')
            }
            if(count==3){
                img3[1].style.transform="translateX(-100%)"
                img3[2].style.transform="translateX(0)"
                img3[3].style.transform="translateX(0)"
                img3[4].style.transform="translateX(0)"
                img3[5].style.transform="translateX(0)"
                img3[6].style.transform="translateX(0)"
                myProgress.style.setProperty('--beforeWidth','10%')
            }
            if(count==4){
                img3[1].style.transform="translateX(-100%)"
                img3[2].style.transform="translateX(-200%)"
                img3[3].style.transform="translateX(0)"
                img3[4].style.transform="translateX(0)"
                img3[5].style.transform="translateX(0)"
                img3[6].style.transform="translateX(0)"
                myProgress.style.setProperty('--beforeWidth','20%')
            }
            if(count==5){
                img3[2].style.transform="translateX(-200%)"
                img3[3].style.transform="translateX(-300%)"
                img3[4].style.transform="translateX(0)"
                img3[5].style.transform="translateX(0)"
                img3[6].style.transform="translateX(0)"
                myProgress.style.setProperty('--beforeWidth','30%')
            }
            if(count==6){
                img3[3].style.transform="translateX(-300%)"
                img3[4].style.transform="translateX(-400%)"
                img3[5].style.transform="translateX(0)"
                img3[6].style.transform="translateX(0)"
                myProgress.style.setProperty('--beforeWidth','40%')
            }
            if(count==7){
                img3[4].style.transform="translateX(-400%)"
                img3[5].style.transform="translateX(-500%)"
                img3[6].style.transform="translateX(0)"
                myProgress.style.setProperty('--beforeWidth','50%');
            }
        count--;
        }
document.querySelector(".next").addEventListener("click",main_transition1);
document.querySelector(".next").addEventListener("click",main_transition2);
document.querySelector(".next").addEventListener("click",main_transition3);
document.querySelector(".prev").addEventListener("click",main_back_transition1);
document.querySelector(".prev").addEventListener("click",main_back_transition2);
document.querySelector(".prev").addEventListener("click",main_back_transition3);